services:
  # order_service_backend:
  #   build: ./backend/order-service/
  #   ports:
  #     - 8082:8082
    
  # user_service_backend:
  #   build: ./backend/user-service/
  #   ports:
  #     - 8081:8081
    
  frontend:
    build: ./frontend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./frontend/cert:/etc/nginx/cert:ro